# Generated by Django 3.0.6 on 2020-05-31 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('template', models.ImageField(upload_to='images/')),
                ('material', models.FileField(blank=True, null=True, upload_to='materials/')),
                ('model', models.FileField(blank=True, null=True, upload_to='models/')),
                ('result_img', models.ImageField(blank=True, null=True, upload_to='result_imgs/')),
                ('result_vid', models.FileField(blank=True, null=True, upload_to='result_vids/')),
                ('result_text', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
