# Generated by Django 3.0.6 on 2020-05-31 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0002_auto_20200531_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='model',
            field=models.FileField(blank=True, null=True, upload_to='models/'),
        ),
    ]
